cookiecuttr.settings:
  type: config_object
  label: 'CookieCuttr settings'
  mapping:
    CookieCutter:
      type: boolean
    hide_parts:
      type: text
      label: 'Hide elements'
    analytics:
      type: boolean
    decline_button:
      type: boolean
    accept_button:
      type: boolean
    reset_button:
      type: boolean
    overlay_enabled:
      type: boolean
    policy_link:
      type: uri
    message:
      type: text
    analytics_message:
      type: text
    what_are_they_link:
      type: uri
    error_message:
      type: text
    notification_location_bottom:
      type: boolean
    disable:
      type: text
    accept_button_text:
      type: text
    decline_button_text:
      type: text
    reset_button_text:
      type: text
    what_are_link_text:
      type: text
    policy_page:
      type: boolean
    policy_page_message:
      type: text
    discreet_link:
      type: boolean
    discreet_link_text:
      type: text
    discreet_position:
      type: text
    domain:
      type: text
