ldap_user.settings:
  type: mapping
  label: Settings
  mapping:
    ldap_user_cron_last_uid_checked:
      type: integer
    ldap_user_conf:
      type: mapping
      mapping:
        drupalAcctProvisionServer:
          label: 'drupalAcctProvisionServer'
          type: string
