# Schema for the xmlsitemap_engines configuration files of the XMLSitemap module.

xmlsitemap_engines.settings:
    type: mapping
    label: 'XMLSitemap engines settings'
    mapping:
        engines:
            type: mapping
            label: 'Engines that will receive the sitemap'
        custom_urls:
            type: mapping
            label: 'Url engines'
        minimum_lifetime:
            type: integer
            label: 'Minumum lifetime for sitemaps'
